### ISSUE TITLE
Getting Error:Transaction reverted: function selector was not recognized and there's no fallback function 

### ISSUE THREAD

**Issue by giftset** [dabit3/polygon-ethereum-nextjs-marketplace#6]
I'm getting following error, and i was looking for a solution to fix this error but it's really hard to find.

I'm new to this solidity and hardhat project.
I hope to get a solution for this.
Help me please!!

`  
Error: Transaction reverted: function selector was not recognized and there's no fallback function
      at NFT.<unrecognized-selector> (contracts/NFT.sol:8)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at HardhatNode.runCall (/Users/lukeskywaka/nft-test/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:503:20)
      at EthModule._callAction (/Users/lukeskywaka/nft-test/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:353:9)
      at HardhatNetworkProvider._sendWithLogging (/Users/lukeskywaka/nft-test/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:129:22)
      at HardhatNetworkProvider.request (/Users/lukeskywaka/nft-test/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:106:18)
      at JsonRpcHandler._handleRequest (/Users/lukeskywaka/nft-test/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:188:20)
      at JsonRpcHandler._handleSingleRequest (/Users/lukeskywaka/nft-test/node_modules/hardhat/src/internal/hardhat-network/jsonrpc/handler.ts:167:17)
`

**Comment by yestinlamptey** [comment]
What is your scenario? Please provide your code-> preferably the function that includes line 8 from NFT.sol

**Comment by nodiscardme** [comment]
> What is your scenario? Please provide your code-> preferably the function that includes line 8 from NFT.sol

```
8. contract NFT is ERC721URIStorage {
9.    using Counters for Counters.Counter;
10.    Counters.Counter private _tokenIds;
11.    address contractAddress;
12.
13.    constructor(address marketplaceAddress) ERC721("Metaverse Tokens", "METT") {
14.        contractAddress = marketplaceAddress;
15.    }
```

**Comment by leinss** [comment]
I've had the same issue:
1. Run `npx hardhat node` in one terminal
2. Deploy the contracts while the node is running 
3. Check that the deployed addresses are correct (I switched nft and the market by accident).
