### ISSUE TITLE
Error: Expected private key to be an Uint8Array with length 32

### ISSUE THREAD

**Issue by Adrenogenesis** [dabit3/polygon-ethereum-nextjs-marketplace#7]
I get an error with `accounts: [privateKey]` 

`gitpod /workspace/polygon-ethereum-nextjs-marketplace $ npx hardhat run scripts/deploy.js --network matic
Error: Expected private key to be an Uint8Array with length 32
    at assert (/workspace/polygon-ethereum-nextjs-marketplace/node_modules/secp256k1/lib/index.js:18:20)
    at isUint8Array (/workspace/polygon-ethereum-nextjs-marketplace/node_modules/secp256k1/lib/index.js:31:7)
    at Object.publicKeyCreate (/workspace/polygon-ethereum-nextjs-marketplace/node_modules/secp256k1/lib/index.js:113:7)
    at Object.exports.privateToPublic (/workspace/polygon-ethereum-nextjs-marketplace/node_modules/hardhat/node_modules/ethereumjs-util/src/account.ts:272:22)
    at exports.privateToAddress (/workspace/polygon-ethereum-nextjs-marketplace/node_modules/hardhat/node_modules/ethereumjs-util/src/account.ts:280:26)
    at LocalAccountsProvider._initializePrivateKeys (/workspace/polygon-ethereum-nextjs-marketplace/node_modules/hardhat/src/internal/core/providers/accounts.ts:169:43)
    at new LocalAccountsProvider (/workspace/polygon-ethereum-nextjs-marketplace/node_modules/hardhat/src/internal/core/providers/accounts.ts:45:10)
    at applyProviderWrappers (/workspace/polygon-ethereum-nextjs-marketplace/node_modules/hardhat/src/internal/core/providers/construction.ts:178:18)
    at Object.createProvider (/workspace/polygon-ethereum-nextjs-marketplace/node_modules/hardhat/src/internal/core/providers/construction.ts:116:27)
    at /workspace/polygon-ethereum-nextjs-marketplace/node_modules/hardhat/src/internal/core/runtime-environment.ts:80:14`

Here is my configuration :

`const privateKeymatic = fs.readFileSync(".secret").toString().trim() || "01234567890123456789";`

with in `.secret` file : 1xxxxxxxxxxxxxxxx....

` matic: {
      url: "https://rpc-mumbai.maticvigil.com/v1/cb00xxxxxxxxxxxxxxxxxxxxxxxxxxxxx...",
      accounts: [privateKeymatic],
    }`

I have tried everything, notably:

(https://hardhat.org/tutorial/deploying-to-a-live-network.html )  configuration recommendation.

Have you an idea about this ?

**Comment by namelessperson0** [comment]
Private key starts with 0x as it is a hex

**Comment by Chibueze864** [comment]
I am having this problem too with sila
